### ISSUE TITLE
Possible use of Singleton design pattern

### ISSUE THREAD

**Issue by andrestoala** [minjoong507/DB_System_project#1]
Hi. I am a student still in the path of learning, I am currently doing an assignment on design pattern and run across your repository.
So i found that you use repeatedly a connection for every test, and in some classes in your project. And here is a suggestion on what to use to evade repeating the same line in every class. Its not the best answer but I trust that you will find a better answer accordingly to your expectations.

## Singleton design pattern
Singleton is a creational design pattern, which ensures that only one object of its kind exists and provides a single point of access to it for any other code.

Singleton has almost the same pros and cons as global variables. Although they’re super-handy, they break the modularity of your code.

https://refactoring.guru/design-patterns/singleton/java/example#example-2

## Suggestion
When i read your readme and your code I noticed that you dont use threads so Im guessing that this repo is for use of an admin and nothing else.
If im right this suggestion may be properly correct.
![1](https://user-images.githubusercontent.com/73241942/102732517-f0949200-4308-11eb-9559-94b012a4ca78.png)
Here is an example code:
![2](https://user-images.githubusercontent.com/73241942/102732605-29346b80-4309-11eb-8bb5-87ed2c26adad.png)
![3](https://user-images.githubusercontent.com/73241942/102732610-2f2a4c80-4309-11eb-98f5-6f8835024482.png)
![4](https://user-images.githubusercontent.com/73241942/102732611-2fc2e300-4309-11eb-8f43-7c6a9f9d7b3d.png)

## Pros & Cons
So there exists some pros and cons in these suggestion of the pattern.
The prons are that you are not using for every class a new connection and you have a super global variable that you instantiate one time per run of the program.
The cons is when you try to implement this project to a higher level of usage, for example multiple users accesing your database (in that case disregard this suggestion and use connection pools).

## Conclusion
Thanks in advance for paying attention to my suggestion.

**Comment by minjoong507** [comment]
Hi! This project is for personal assignments, so there're some unnecessary code may exist. Thanks for your suggestion 👍

**Comment by andrestoala** [comment]
Glad to be of help. Im still learning the ropes of programming so is very encouraging to see replies. Thanks and keep up your amazing work.
