### ISSUE TITLE
Suggestion for uses of queries

### ISSUE THREAD

**Issue by andrestoala** [minjoong507/DB_System_project#2]
## Composite design pattern
Composite is a structural design pattern that lets you compose objects into tree structures and then work with these structures as if they were individual objects. 
https://refactoring.guru/design-patterns/composite

## Usage of composite 
I found that you use a lot of queries what if you can pack them all together so you dont repeat code. For example in some test classes and in the main one, u use a lot of the queries.
![DD](https://user-images.githubusercontent.com/73241942/102739603-93eea280-431b-11eb-9972-8041bdfea63c.png)

## Suggestion
![Diagrama de clases UML - Página 4](https://user-images.githubusercontent.com/73241942/102739902-5b02fd80-431c-11eb-83e3-c76d3072695f.png)
I recommend group some of the codes that you use constantly to preview some data of the database and use the diagram i share accordingly to your needs. With this suggestion you have combinations of queries and may as well apply polimorphism or recursive methods.

## Regards
Thanks for paying attention.

**Comment by minjoong507** [comment]
Thank you. I'll reflect your suggestion :)
